# Generated by Django 2.2.6 on 2019-10-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterpedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
