# Generated by Django 2.2.6 on 2019-11-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterpedia', '0003_auto_20191101_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
