# Generated by Django 2.2.6 on 2019-11-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterpedia', '0004_auto_20191101_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
