# Generated by Django 2.2.6 on 2019-11-02 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsterpedia', '0005_auto_20191101_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='species',
        ),
        migrations.AddField(
            model_name='monster',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monsterpedia.Species'),
        ),
    ]
